const assert=require('node:assert/strict');require('../dist/model.js');const M=globalThis.RosterModel,d=require('../dist/data.json');
const army=d.armies.find(a=>a.name==="Azog's Hunters"),bolg=d.profiles.find(p=>p.name==='Bolg, Spawn of Azog'),fimbul=d.profiles.find(p=>p.name==='Fimbul, Hunter Orc Captain'),orc=d.profiles.find(p=>p.name==='Hunter Orc Warrior'&&M.membership(p,army));assert(orc);
let r=M.migrate(null,d);assert.throws(()=>M.addEntry(r,orc,army,[],null));M.addEntry(r,bolg,army,[]);const b=r.active;M.addEntry(r,orc,army,[],b,6);M.addEntry(r,fimbul,army,[]);const f=r.active;M.addEntry(r,orc,army,[],f,3);assert.equal(r.warbands.length,2);assert.equal(M.capacity(r.warbands[0],army,d),15);assert.equal(M.capacity(r.warbands[1],army,d),12);const total=M.total(r,d.profiles,d.armies);assert.equal(total,bolg.points+fimbul.points+9*orc.points);const key=r.warbands[0].entries[0].key;M.move(r,b,key,f,2);assert.equal(M.warriorCount(r.warbands[0]),4);assert.equal(M.warriorCount(r.warbands[1]),5);assert.equal(M.total(r,d.profiles,d.armies),total);const before=JSON.stringify(r);assert.throws(()=>M.move(r,b,key,f,20));assert.equal(JSON.stringify(r),before);assert.throws(()=>M.addEntry(r,bolg,army,[]));M.removeWarband(r,b,f);assert.equal(r.warbands.length,1);assert.equal(M.warriorCount(r.warbands[0]),9);assert.equal(M.total(r,d.profiles,d.armies),total-bolg.points);assert.equal(r.active,f);
const old={name:'Preserved draft',limit:500,army:army.id,entries:[{profile:bolg.id,options:[],quantity:1,key:bolg.id+':'},{profile:orc.id,options:[],quantity:7,key:orc.id+':'}]};r=M.migrate(old,d);assert.equal(r.warbands.length,1);assert.equal(r.unassigned[0].quantity,7);M.move(r,'unassigned',orc.id+':',r.active,7);assert.equal(r.unassigned.length,0);assert.equal(M.warriorCount(r.warbands[0]),7);M.removeWarband(r,r.active);assert.equal(M.allEntries(r).length,0);assert.equal(r.army,null);const ind=d.profiles.find(p=>p.role==='Hero'&&p.armies.some(x=>x.tier==='Independent Hero'));const ia=d.armies.find(a=>ind.armies.some(x=>x.army===a.id&&x.tier==='Independent Hero'));const war=d.profiles.find(p=>p.role!=='Hero'&&!p.unique&&M.membership(p,ia));const cap=d.profiles.find(p=>p.role==='Hero'&&!p.unique&&M.membership(p,ia)&&M.membership(p,ia).tier!=='Independent Hero');
r=M.migrate(null,d);M.addEntry(r,ind,ia,[],null,1,d);const iw=r.active;assert(M.independent(r.warbands[0],ia,d));assert.equal(M.capacity(r.warbands[0],ia,d),0);assert.throws(()=>M.addEntry(r,war,ia,[],iw,1,d),/Independent Heroes may never have Followers/);
if(cap){M.addEntry(r,cap,ia,[],null,1,d);const cw=r.active;M.addEntry(r,war,ia,[],cw,2,d);const k=r.warbands[1].entries[0].key;assert.throws(()=>M.move(r,cw,k,iw,1,d),/Independent/);assert.throws(()=>M.removeWarband(r,cw,iw,d),/Independent/);assert.equal(M.warriorCount(r.warbands[0]),0);}
const mi=d.armies.find(a=>a.name==='Muster of Isengard'),saru=d.profiles.find(p=>p.name==='Saruman'&&p.role==='Hero'),gh=d.profiles.find(p=>p.id==='heroes-226'),gw=d.profiles.find(p=>p.id==='warriors-112'),uw=d.profiles.find(p=>p.name==='Uruk-hai Warrior'&&M.membership(p,mi));
r=M.migrate(null,d);M.addEntry(r,saru,mi,[],null,1,d);const sw=r.active;M.addEntry(r,gw,mi,[],sw,1,d);M.addEntry(r,uw,mi,[],sw,3,d);assert.equal(M.warriorCount(r.warbands[0],d),3);assert.equal(M.warriorCount(r.warbands[0]),4);assert.throws(()=>M.addEntry(r,gh,mi,[],null,1,d),/unique/);
const nd=M.withoutLegacy(d);assert(nd.armies.length&&nd.armies.every(a=>!a.legacy));assert(nd.profiles.every(p=>!p.legacy&&p.armies.length&&p.armies.every(x=>nd.armies.some(a=>a.id===x.army))));assert(!nd.profiles.some(p=>p.name==='Khamûl the Easterling'));
const legacyArmy=d.armies.find(a=>a.legacy),lp=d.profiles.find(p=>p.role==='Hero'&&M.membership(p,legacyArmy));r=M.migrate(null,d);M.addEntry(r,lp,legacyArmy,[],null,1,d);r=M.prune(r,nd);assert.equal(r.army,null);assert.equal(M.allEntries(r).length,0);
const kh=d.armies.find(a=>a.name==='Army of the Great Eye'),ringw=d.profiles.find(p=>p.name==='Ringwraith C'),kham=d.profiles.find(p=>p.name==='Khamûl the Easterling'&&p.role==='Hero');r=M.migrate(null,d);M.addEntry(r,ringw,kh,[],null,1,d);M.addEntry(r,kham,kh,[],null,1,d);r=M.prune(r,nd);assert.equal(r.warbands.length,1);assert.equal(r.army,kh.id);
const kr=nd.armies.find(a=>a.name==='Kingdom of Rohan'),th=nd.profiles.find(p=>p.name==='Theoden, King of Rohan'),oid=n=>th.options.find(o=>o.name===n).id;
let es=M.effectiveStats(th,kr,[oid('Shield')],nd);assert.equal(es.stats.defence,th.stats.defence+1);assert.equal(es.changed.defence,1);
es=M.effectiveStats(th,kr,[oid('Shield'),oid('Exchange armour for heavy armour'),oid('Snowmane with Armour')],nd);assert.equal(es.stats.defence,th.stats.defence+2);assert(es.mount&&es.mount.stats.movement>=10);
const fr=nd.profiles.find(p=>p.name==='Frodo Baggins'&&p.role==='Hero'),fe=nd.armies.find(a=>a.name==='The Fellowship');es=M.effectiveStats(fr,fe,[fr.options.find(o=>o.name==='Mithril Coat').id],nd);assert.equal(es.stats.defence,fr.stats.defence+3);
assert.equal(M.effectiveStats(th,kr,[],nd).stats.defence,th.stats.defence);
console.log('PASS: hero groups, warrior assignment, tier capacities, transfers, point preservation, atomic failures, unique heroes, removal, independent heroes, no-space followers, unique characters across entries, Legacy filtering, equipment stat changes, and old-draft migration.');
